export const scaleFactor = 4;

export const dialogueData = {
  'treasure_chest': "I wonder what's in here...",
  'welcome': "Welcome to Heliopolis! This is a fan website where you can learn more about <a href='https://heliohost.org/' target='_blank'>HelioHost</a> and their services.<p>All details have been sourced from the <a href='https://wiki.helionet.org/' target='_blank'>HelioHost Wiki</a>.<p>Please feel free to interact with your surroundings: Read signs, hug trees, talk to the wildlife, and walk around some more.<p>Running is strictly forbidden.",
  'one': "Like most places, there are some <a href='https://wiki.helionet.org/Terms' target='_blank'>rules</a> everone needs to follow. Here's a big 1!<br><br>What does the big 1 have to do with the rules? Well, everyone is only allowed <strong>one</strong> account on HelioHost. 1. One. <strong>ONE</strong>. People who make more than one account will be <a href='https://wiki.helionet.org/Suspension_Policy#Duplicate_Accounts' target='_blank'>suspended</a>. Since we can have <a href='https://wiki.helionet.org/Addon_Domains' target='_blank'>up to 10 domains on an account</a>, and even <a href='https://wiki.helionet.org/Donations_for_Increased_Storage' target='_blank'>upgrade our storage</a> if needed, there's really no need for multiple accounts anyway. <p>This rule helps HelioHost provide free accounts to as many people as possible.",
  'cpu': "HelioHost accounts have a limit of <a href='https://wiki.helionet.org/Suspension_Policy#Account_Load_Limits' target='_blank'>no more than 10,000 CPU usage</a> per day.<p>If that's not enough, they also have <a href='https://wiki.helionet.org/Morty' target='_blank'>scaling hosting</a>! For people who need even more CPUs, they offer a range of <a href='https://heliohost.org/vps/' target='_blank'>VPS plans</a>, with a 10% discount when paying for 6 months upfront.",
  'memory': "HelioHost accounts have a memory limit of <a href='https://wiki.helionet.org/Suspension_Policy#Account_Load_Limits' target='_blank'>no more than 100 GB</a> per day.<p>If that's not enough, they also have <a href='https://wiki.helionet.org/Morty' target='_blank'>scaling hosting</a>! For people who need even more memory, they offer a range of <a href='https://heliohost.org/vps/' target='_blank'>VPS plans</a>, with a 10% discount when paying for 6 months upfront.",
  'frog': "I wasn't always a frog, you know...<p><em>*sad frog noises*</em><p>If only I had followed the <a href='https://wiki.helionet.org/Terms' target='_blank'>rules</a>!",
  '20': "<a href='https://heliohost.org/' target='_blank'>HelioHost</a> has been offering free web hosting services to the community for over 20 years!<br><br>You can <a href='https://heliohost.org/donate/' target='_blank'>make a donation</a> to help support their efforts, or check out some <a href='https://wiki.helionet.org/How_You_Can_Help' target='_blank'>other ways you can help</a>.",
};